### ISSUE TITLE
Apk file can't show property detail package

### ISSUE THREAD

**Issue by surattum** [allangoing/apkshellext#34]
I uninstall previous version (APKShellext2_01) and install last version (apkshellext2_01_5674_27010)
APK file can't show property detail package

![2015-07-17_0-19-50](https://cloud.githubusercontent.com/assets/13364144/8731101/4df32d32-2c1f-11e5-816f-04deec978a09.jpg)

Note: Install on Windows 8.1 Pro 64bit

**Comment by kkguo** [comment]
So, welcome back.
I assume you are talking about the "information tip", the light yellow bubble.
I guess you are using other 3rd party tool to manage apk file at the same time, so the registry is changed by that tool.

You could verify by checking the registry? Here are steps:
1. Start -> run -> "regedit" (you may prompt UAC, check yes of course)
2. Go to key HKEY_CLASSES_ROOT/.apk check the (Default) key value, note it down, if value not set, go to step 4
3. Go to key HKEY_CLASSES_ROOT/<name you note down just now>
4. Check subkey shellex/{00021500-0000-0000-C000-000000000046}, you should see value is {946435a5-fe96-416d-99db-e94ee9fb46c8}
5. if not, please quit any tool related to apk file, kill any service or background process. re-run the install.bat, you should see the info tip now. if not, please let me know.

Actually if the tool change the key I mentioned above, windows should come up UAC, unless you are running administrator account, be careful to those request, don't give them authority if you don't know what is going on.

please let me know your result.

**Comment by surattum** [comment]
Yes "information tip" It does not work
I test again
1. I uninstall and remove HKEY_CLASSES_ROOT/.apk on regedit and reboot PC
2. I install and restart_explorer, But it does not work

please view regedit
![2015-07-18_2-39-09](https://cloud.githubusercontent.com/assets/13364144/8755867/3cf6da0e-2cf8-11e5-95f4-95b84f9dacdd.jpg)

Thank you

**Comment by kkguo** [comment]
Thanks for the snap shot. looks like register does work.
what is the value of default key of HKEY_CLASSES_ROOT/.apk? what you see
now in the tip bubble?

surattum notifications@github.com于2015年7月17日周五 下午3:55写道：

**Comment by kkguo** [comment]
@surattum, is the problem resolved? Please provide more information for this issue, or I will close it as resolved later

**Comment by surattum** [comment]
I install latest version apkshellext2_01_5676_26162
ฺฺBut the problem has not been resolve.
And a additional problems "file in use" I cannot move and remove file apk
![2015-07-23_9-21-47](https://cloud.githubusercontent.com/assets/13364144/8841781/4d2c648e-311c-11e5-8698-1da6ffcc3cb1.jpg)

**Comment by SmartManoj** [comment]
@surattum  Same problem here and i cannot rename the files also

**Comment by SmartManoj** [comment]
@kkguo Please add a feature that automatically rename the apk files
Please quickly update with new features

**Comment by kkguo** [comment]
please try the latest fix:
https://github.com/kkguo/apkshellext/blob/releases/apkshellext2_0.1.5681.40033.zip?raw=true

You may need to restart the explorer to release the handler from last version.

@SmartManoj, regarding the automatically rename, can you raise another issue so we could trace it?
and also please describe the scenario. Do you want the extension rename the file when see the file? or  scan all the apk on your driver and change the name? I'm not sure user will like their file name got changed without notice.

@surattum, please let me know if this fix also resolved the tooltip issue, or not, thanks!

**Comment by surattum** [comment]
I installed latest version (apkshellext2_0.1.5681.40033)
case: file in use
problem resolved.

case:tooltip issue
my computer problem has not been resolve

But I installed latest version to new computer tooltip work (never install apkshellext)
my computer  problem history install APKShellext2_01 (issue uninstall)

**Comment by kkguo** [comment]
can you please dump the whole registry key HKEY_CLASSES_ROOT/.apk

**Comment by surattum** [comment]
My computer problem resolved.
OK Thank you

My solution
first I install and uninstall apkshellext1 (ver2.2)
second I installed latest version (apkshellext2_0.1.5681.40033)
![2015-07-23_12-03-13](https://cloud.githubusercontent.com/assets/13364144/8843555/355507cc-3134-11e5-8538-adf7a13b52ac.jpg)

**Comment by kkguo** [comment]
thanks for reply, now I close this, if you see same problem, please feel free to re-open.
