### ISSUE TITLE
APK is "open in Explorer"

### ISSUE THREAD

**Issue by GuyInDogSuit** [allangoing/apkshellext#35]
APK files cannot be moved, deleted, or renamed because according to Windows, they are "open in Explorer." OS: Windows 7 Ultimate x64. Version: 0.1.5676.26162

![untitled-1](https://cloud.githubusercontent.com/assets/13460691/8841749/9985434e-30a6-11e5-9afa-684cc86b2072.jpg)

**Comment by SmartManoj** [comment]
@GuyInDogSuit same problem

**Comment by kkguo** [comment]
Please try this fix, the apk reader had a leak
https://github.com/kkguo/apkshellext/blob/releases/apkshellext2_0.1.5681.40033.zip?raw=true
