### ISSUE TITLE
Icon not clear

### ISSUE THREAD

**Issue by surattum** [allangoing/apkshellext#36]
latest version (0.1.5714.19596) icon not clear and button does not link to web
![2015-09-19_0-29-35](https://cloud.githubusercontent.com/assets/13364144/9966782/f9eb6caa-5e68-11e5-8728-d1249c2e2b2e.png)
![2015-09-19_0-52-14](https://cloud.githubusercontent.com/assets/13364144/9966796/077822b4-5e69-11e5-9cc6-39f8b4fee56b.png)

**Comment by kkguo** [comment]
next release will use the clearest icon from the package, thanks!

**Comment by kkguo** [comment]
some apk still not clear.

**Comment by kkguo** [comment]
The reason for unclear icon is, windows will request several certain resolutions: 16x16, 32x32,64x64,256x256, and the icon from the apk normally is not any of these. re-size will lose some resolution. Trying to resolve this by using the most closed resolution icon from apk.
And even 256x256 is not clear enough sometimes, I'm creating thumbnail handler for that, but there is another problem, thumbnail is caching, and hard to refresh manually. Still thinking...

**Comment by kkguo** [comment]
in the [release v0.1.5770.22958](https://github.com/kkguo/apkshellext/releases/tag/v0.1.5770.22958), thumbnail is enabled, will be shown while need icon larger than 256x256
