### ISSUE TITLE
Add the option to not show icons in context menu

### ISSUE THREAD

**Issue by sylveon** [allangoing/apkshellext#37]
It would be cool to do that.

**Comment by kkguo** [comment]
so you don't like the idea of showing the icon in context menu. Can you let me know more about your concern? the performance? or it confuses you?

**Comment by sylveon** [comment]
Consistency (All other entries do not show icons: 
![capture](https://cloud.githubusercontent.com/assets/6440374/10168215/d5b42208-6699-11e5-96cf-d46705923a5d.PNG)

**Comment by sylveon** [comment]
And it's the option, so we can change it in the settings for showing it or not.

**Comment by kkguo** [comment]
Sure, accepted
