### ISSUE TITLE
Multiple updater bugs

### ISSUE THREAD

**Issue by sylveon** [allangoing/apkshellext#40]
- The updater marks it is on the latest version when offline.
- The updates checks during an infinite time when online and the program is up-to-date.  

Except that, it works well.

**Comment by kkguo** [comment]
hmm, probably the offline status confuse it.
will check this.

**Comment by kkguo** [comment]
in [release v0.1.5770.22958](https://github.com/kkguo/apkshellext/releases/tag/v0.1.5770.22958), update only check once each day.
