### ISSUE TITLE
Installing on Windows 10 without Admin cmd window results in endless popups

### ISSUE THREAD

**Issue by archon810** [allangoing/apkshellext#41]
Hi,

I just downloaded the latest version and tried to run install.bat from a non-admin cmd shell. It just keeps endlessly popping up new cmd windows and never actually requesting the admin permission (I have UAC turned off).

Observe: http://i.imgur.com/JcIcWOw.gifv.

**Comment by kkguo** [comment]
Regarding "UAC turned off", do you mean you set the UAC setting to "never notify"?
The installation process need to run regasm.exe and will write into registry. That's why it does need admin authority.
The batch file suppose to output a vbs script for raising UAC, but the code is quite old, probably it's not suitable for win10.
I make the install.bat instead of a install.exe because I don't want to hide installation details as I can get your admin.
I will either fix this or find another solution.
For now, if you just want to install it, please "run as admin"

**Comment by archon810** [comment]
Correct - Never notify.

Admin installation works fine indeed.

**Comment by kkguo** [comment]
That's really wired, I pull down the bar to "never notify" (which I don't think it's good habit :smiling_imp:), but I run through the install.bat without problem under win7 enterprise 64
Need to try on a win10.

One more thing needs to confirm, is your account is an admin and in admin group?

**Comment by tprochazka** [comment]
I have the same problem on Windows 7 Profesional.
I doesn't have turned off UAC
It normally ask for permission first time and it stuck in endless popups
I tried run directly with admin permissions and it does the same.

**Comment by kkguo** [comment]
I think the problem is in the code of checking permission.
@archon810 @tprochazka , can you please list me your os version? 32bits or 64bits?
can you please try run 
"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
in cmd with and without admin, and let me know the result?
Thx.

**Comment by kkguo** [comment]
Tested on win10 home 64bit, win7 enterprise 64bit, didn't see problem
Don't have a 32bits windows yet...

**Comment by archon810** [comment]
I am on Windows 10 x64, but admin install worked, as I mentioned.

**Comment by archon810** [comment]
Without admin:

```
C:\Windows\System32>"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
Access is denied.
```

With admin:

```
C:\WINDOWS\system32>"%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
C:\WINDOWS\system32\config\SYSTEM NT AUTHORITY\SYSTEM:F
                                  BUILTIN\Administrators:F
```

**Comment by kkguo** [comment]
@archon810 thanks, and that is what I expect.
Please try the updated install.bat here, it should stop the endless loop. (remove ".txt" after downloading)
[install.bat.txt](https://github.com/kkguo/apkshellext/files/10538/install.bat.txt)

**Comment by tprochazka** [comment]
Tested install.bat from you last post and it alway write

```
  Cannot elevate administrator privilege
  Please try again with "Run as Administrator"
  Press any key to continue . . .
```

Also when I run it by "Run as Administrator", wey weird, but no endless loop.

I have 64 bit OS.

**Comment by steelew** [comment]
Update: UAC settings change didn't fix it. I also tried the new install.bat.txt and that didn't work, same results. 

I right clicked and chose "run as admin"  and the cmd window made it look like everything worked but nothing has changed and there is no addition to my context menu. I also tried the restart explorer.bat but still nothing. Do I need to change my UAC setting for this to work?
![apk](https://cloud.githubusercontent.com/assets/4789852/10411378/2005bebc-6f18-11e5-8b9b-e75a000f086a.png)

**Comment by kkguo** [comment]
@steelew Can you please export this registry key?
HKEY_CLASSES_ROOT.apk

You should see:
[HKEY_CLASSES_ROOT.apk\DefaultIcon]
@="%1"
"SharpShell_Backup_DefaultIcon"="%1"

[HKEY_CLASSES_ROOT.apk\shellex]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers\ApkContextMenu]
@="{dcb629fc-f86f-456f-8e24-98b9b2643a9b}"

[HKEY_CLASSES_ROOT.apk\shellex\IconHandler]
@="{1f869cee-4fda-35d9-896f-43975a87d1f6}"

[HKEY_CLASSES_ROOT.apk\shellex{00021500-0000-0000-C000-000000000046}]
@="{946435a5-fe96-416d-99db-e94ee9fb46c8}"

[HKEY_CLASSES_ROOT.apk\shellex{e357fccd-a995-4576-b01f-234630154e96}]
@="{d747c5a7-2f66-4b7d-8301-8531838e4ed3}"

**Comment by ghost** [comment]
Hi i asked author for help and with his tremendous help i got  it working. 

I have had 7zip, pure apk install and virtuous ten studio and i uninstalled them. Then deleted registeries with ccleaner registery cleaner and then tried to install with admin privilages and i got it working. 

Now I have it fully working. I had problems with all of them actually when i uninstalled it one by one i got it working.

**Comment by steelew** [comment]
I tried getting rid of andyapk and 7zip then running ccleaner and rebooting
but I have had no luck. I exported the HKEY then did all that stufff then
re-exported. I tried again to install and still no luck. Thanks for helping
me.

-Wil

On Sat, Oct 10, 2015 at 8:59 PM, Jingang Guo, KK notifications@github.com
wrote:

> @steelew https://github.com/steelew Can you please export this registry
> key?
> HKEY_CLASSES_ROOT.apk
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kkguo/apkshellext/issues/41#issuecomment-147152159.

﻿Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT.apk]
@="AndyAPK"

[HKEY_CLASSES_ROOT.apk\DefaultIcon]
@="%1"

[HKEY_CLASSES_ROOT.apk\shellex]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers]

﻿Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT.apk]
@="AndyAPK"

[HKEY_CLASSES_ROOT.apk\DefaultIcon]
@="%1"

[HKEY_CLASSES_ROOT.apk\shellex]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers]

**Comment by kkguo** [comment]
@steelew, as your registry setting shows, your .apk is still binding to "AndyAPK", Please check key
[HKEY_CLASSES_ROOT\AndyAPK]
Please check IconHandler & ContextMenuHandler under this key.

You can also just remove .apk key and run the install.bat. (remember to back-up)
I never run AndyAPK, but I just guess it overwrite the registry.

@steelew, @ravjani & all others
This is a bit off topic, I create another issue #46 to trace installation failure.
And also I gave a temporary solution, please try.

**Comment by steelew** [comment]
I got rid of the .apk entry and all of the ANDYAPK entries I could find. I restarted explorer and tried to re-install with no luck. I also found entries for bluestacks and got rid of those. The only thing that I'm not sure of, is that it might be Nexus root tool kit. I don't want to get rid of it so hopefully there is another way. Thanks

**Comment by kkguo** [comment]
@steelew I will answer you in another thread #46

**Comment by kkguo** [comment]
In [release v0.1.5770.22958](https://github.com/kkguo/apkshellext/releases/tag/v0.1.5770.22958), will not loop, if install is not success because of UAC, you will get a information, and you need "Run as Administrator"
