### ISSUE TITLE
APK icon doesn't show in Properties randomly

### ISSUE THREAD

**Issue by archon810** [allangoing/apkshellext#42]
Hi,

Is it possible to make the APK icon also show in Properties, which is I think the same value Total Commander uses as well? Right now it only seems to show up in Explorer.

![image](https://cloud.githubusercontent.com/assets/469543/10229209/d04d9efa-682b-11e5-847c-02d1f66cafe6.png)

**Comment by kkguo** [comment]
I think it's showing up with icon in the explorer, (win7, enterprise 64bit):
![image](https://cloud.githubusercontent.com/assets/485503/10229545/c1e994ac-6846-11e5-8d2a-9ae1474a3245.png)
But again, probably it's doesn't work for win10.
But looks like you opened the Properties window from Total commander, right?
I'm not sure how total commander requests icons, if it's using windows api, should be ok, needs more inspection.

**Comment by archon810** [comment]
It's weird. From Explorer, I did manage to see the icon once in Properties. But not the other 5 times. Most of the time it shows this, even when accessed from Explorer:

![image](https://cloud.githubusercontent.com/assets/469543/10229748/874b5c44-682e-11e5-9469-686140fb5f8e.png)

**Comment by sylveon** [comment]
@archon18 Weird...:
![capture](https://cloud.githubusercontent.com/assets/6440374/10229875/3468fcd8-6848-11e5-9258-f8b132dc6660.PNG)
It show for apk, ipa, appx, appxbundle for me... Try reinstalling the shell extension.

**Comment by kkguo** [comment]
@charlesmilette, thanks for confirm.
@archon810, can you test more apks? and please send this paypal apk to me so I can try from my side.
And I doubt the tool APK-Info, does it steal the registry?

**Comment by archon810** [comment]
I tried another 3, they're all the same.

APK-Info is just a program that shows some apk info, it doesn't need the registry AFAIK. http://forum.xda-developers.com/showthread.php?t=2359373

**Comment by archon810** [comment]
And now Explorer is showing them. I don't understand this randomness. Total Commander still doesn't though.

![image](http://i.imgur.com/Dn7omHa.png)

**Comment by archon810** [comment]
Btw, from the screenshot, it's obvious you're selecting a very low res icon whereas most apps ship with much higher res ones. I think you should attempt to look at the best res.

aapt dump badging output for FX apk:

```
application-icon-160:'res/drawable-mdpi-v4/ic_launcher.png'
application-icon-213:'res/drawable-hdpi-v4/ic_launcher.png'
application-icon-240:'res/drawable-hdpi-v4/ic_launcher.png'
application-icon-320:'res/drawable-xhdpi-v4/ic_launcher.png'
application-icon-480:'res/drawable-xxhdpi-v4/ic_launcher.png'
application-icon-640:'res/drawable-xxhdpi-v4/ic_launcher.png'
application-icon-65535:'res/drawable-xxhdpi-v4/ic_launcher.png'
```

**Comment by kkguo** [comment]
As APK-info is showing up in Properties window, it probably have touched the registry, or you have manually set it as the default "open-with" method. But NO worry, looks like it will not interfere apkshellext.

I have tried to chose the highest resolution png according to configuration, but actually typical icon handler only accept at most 32x32. I'm looking for another way.

Thanks for response, I will rephrase the title.

**Comment by kkguo** [comment]
I reopened #36.

**Comment by kkguo** [comment]
correction: windows will request upto 256x256 size of icons

**Comment by kkguo** [comment]
@archon810, please check if you still have problem with the latest release or not, I'm going to close this for now, please feel free to re-open if you still see problem.
