### ISSUE TITLE
Request: please show more info when hovering, or at least allow to use original hovering info

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [allangoing/apkshellext#44]
Previous one showed file size, but now it doesn't show it.
There are other stuff that were shown too, but this one is what I look at usually.

**Comment by kkguo** [comment]
There will be more option for tipinfo.
@AndroidDeveloperLB, do you have a preference which info you want most?

**Comment by AndroidDeveloperLB** [comment]
I wish it to have at least the previous information, but for now, the most
important thing for me is the file size. Maybe also file modified date.

**Comment by kkguo** [comment]
In  [release v0.1.5770.22958](https://github.com/kkguo/apkshellext/releases/tag/v0.1.5770.22958), the hovering info can be customized with different information.

**Comment by AndroidDeveloperLB** [comment]
Does it get auto-updated? Or should I check the website myself and manually do it?

**Comment by kkguo** [comment]
no, you need to download it manually, it's a bit harder to get it
auto-updated..

AndroidDeveloperLB notifications@github.com于2015年10月19日周一 下午3:47写道：

**Comment by AndroidDeveloperLB** [comment]
Can you please add such a thing? maybe make it check for updates every day or week ?

**Comment by kkguo** [comment]
It's currently checking new version once every day, and will show in the preference window.
I'm considering to show up a update menu in the context menu once update available.
I don't want to disturb user much, as most of the people just concern about the show-icon-feature.
~~BTW-, you can subscribe telegram channel https://telegram.me/apkshellext for new release.~~
I create a group on telegram, check it out.. https://telegram.me/joinchat/BrcZsQAtOKWeA7ThTyq3Ug

**Comment by AndroidDeveloperLB** [comment]
You can just show a notification in the task bar in case there is a new update.

**Comment by sylveon** [comment]
@AndroidDeveloperLB impossible without a background running program. this is just an shell extension, wich means thta it runs anything in the background

**Comment by AndroidDeveloperLB** [comment]
@charlesmilette Well if it runs anything in the background, why not also check for updates?

**Comment by sylveon** [comment]
@AndroidDeveloperLB by that i meant that no background process is ran, a shell extension is just a dll for explorer to handle a file. it does not have a background running process, so it can't check for updates. except if someone develops a full separated app that checks and notifies you.

**Comment by AndroidDeveloperLB** [comment]
What if when you use it, it checks for updates (in case there was a
day/week since the last time it did it) ?
Is this possible?

**Comment by sylveon** [comment]
since the shell extension is initialized for each image, it will mean for each file you'll get a notification. Imagine opening a folder containing 100 apks... But adding an entry in the context menu for files will be possible.

**Comment by kkguo** [comment]
To run in background is not a problem, but where to show user? It was in
the preference window opened from context menu, now it's checking update
when showing icon, only the first thread will do that, and once a day,
result is saved in user settings.

**Comment by sylveon** [comment]
@kkguo Using windows 10's notifications center/windows' taskbar popup api?

**Comment by kkguo** [comment]
I need to consider other windows user, call a ballon is ok, but i cannot
make an icon in taskbar, as i don't have a process

**Comment by sylveon** [comment]
an overlay in the icon?

**Comment by kkguo** [comment]
Yes, it's possible, but it's not good to force user to update. I will add a
submenu in context menu, showing the new version info. I think it's the
best place for now.

**Comment by AndroidDeveloperLB** [comment]
ok, thank you. you can also add the check to when the user hovers over an item.
