### ISSUE TITLE
Installation is good, but still not showing icons for apk files.

### ISSUE THREAD

**Issue by kkguo** [allangoing/apkshellext#46]
As the discussion at the lower part of #41, there is an issue if you installed other apk tool, the icon handler may not registered correctly. I'm trying to figure this out, but meanwhile, I would like to maintain a list of conflict software.

Known:
    amiduos
    andyapk
    7zip ?
#### Temporary solution:

**I assume you understand what I'm saying and what you are doing!!**
1. Uninstall them is the most straight forward way, but they may left registry setting in system registry. You may delete HKEY_CLASSES_ROOT.apk key, (before that, do a full backup), try install.bat again.
2.There is another way, can keep the other software working, but not guarantee works for all situation.
   Firstly find the Default key value of HKEY_CLASSES_ROOT.apk, say it's someapp
   goto key HKEY_CLASSES_ROOT\someapp, create following key
[HKEY_CLASSES_ROOT\someapp\shellex]

[HKEY_CLASSES_ROOT\someapp\shellex\ContextMenuHandlers]

[HKEY_CLASSES_ROOT\someapp\shellex\ContextMenuHandlers\ApkContextMenu]
@="{dcb629fc-f86f-456f-8e24-98b9b2643a9b}"

[HKEY_CLASSES_ROOT\someapp\shellex\IconHandler]
@="{1f869cee-4fda-35d9-896f-43975a87d1f6}"

[HKEY_CLASSES_ROOT\someapp\shellex{00021500-0000-0000-C000-000000000046}]
@="{946435a5-fe96-416d-99db-e94ee9fb46c8}"

[HKEY_CLASSES_ROOT\someapp\shellex{e357fccd-a995-4576-b01f-234630154e96}]
@="{d747c5a7-2f66-4b7d-8301-8531838e4ed3}"

**Comment by kkguo** [comment]
@steelew I have Nexus root kit installed as well, but I didn't see problem.
Can you please dump the registry to me, I concern about following keys:
HKEY_CLASSES_ROOT.apk
HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}

and if the (Default) value for .apk is set, please also dump
HKEY_CLASSES_ROOT<.apk default value>

**Comment by steelew** [comment]
Looks like a lot of default value not set. Thanks for working on this.

**Comment by steelew** [comment]
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT.apk]

[HKEY_CLASSES_ROOT.apk\DefaultIcon]
@="%1"
"SharpShell_Backup_DefaultIcon"="%1"

[HKEY_CLASSES_ROOT.apk\shellex]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers\ApkContextMenu]
@="{dcb629fc-f86f-456f-8e24-98b9b2643a9b}"

[HKEY_CLASSES_ROOT.apk\shellex\IconHandler]
@="{1f869cee-4fda-35d9-896f-43975a87d1f6}"

[HKEY_CLASSES_ROOT.apk\shellex{00021500-0000-0000-C000-000000000046}]
@="{946435a5-fe96-416d-99db-e94ee9fb46c8}"

---

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}]
@="ApkShellext2.ApkIconHandler"

[HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}\Implemented Categories]

[HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}\Implemented Categories{62C8FE65-4EBB-45e7-B440-6E39B2CDBF29}]

[HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}\InprocServer32]
@="mscoree.dll"
"ThreadingModel"="Both"
"Class"="ApkShellext2.ApkIconHandler"
"Assembly"="ApkShellext2, Version=0.1.5751.17210, Culture=neutral, PublicKeyToken=c580a4e497a7aae4"
"RuntimeVersion"="v4.0.30319"
"CodeBase"="file:///F:/Phones/z apkshellext2_0.1.5751.17210/ApkShellext2.DLL"

[HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}\InprocServer32\0.1.5751.17210]
"Class"="ApkShellext2.ApkIconHandler"
"Assembly"="ApkShellext2, Version=0.1.5751.17210, Culture=neutral, PublicKeyToken=c580a4e497a7aae4"
"RuntimeVersion"="v4.0.30319"
"CodeBase"="file:///F:/Phones/z apkshellext2_0.1.5751.17210/ApkShellext2.DLL"

[HKEY_CLASSES_ROOT\CLSID{1F869CEE-4FDA-35D9-896F-43975A87D1F6}\ProgId]
@="ApkShellext2.ApkIconHandler"

**Comment by steelew** [comment]
(Remove the .png file extension)
![reg files zip](https://cloud.githubusercontent.com/assets/4789852/10453243/86b2a794-715f-11e5-8767-973b465fc024.png)

**Comment by kkguo** [comment]
@steelew, thanks for update, looks like your setting is ok, i will check more. 
i would like you try to download an appxbundle file, or ipa file, if their icon shows correctly, at least prove that the registry works

**Comment by steelew** [comment]
Here is what I saw when hovering over .ipa files, they are a couple of
years old so that could be why I get the "fail to read file".

[image: Inline image 1]

**Comment by kkguo** [comment]
@steelew I think the handler is registered and working, although you see "fail to read file", nothing else will show this out. And does the tooltip working for apk file too?

I didn't see problem with your register setting, but I'm attaching a debug dll. You probably need to uninstall or restart the explorer before you can overwrite the old one.

Please change the registry to enable the log before install:
[HKEY_LOCAL_MACHINE\SOFTWARE\SharpShell]
"LoggingMode"=dword:00000004
"LogPath"=<your\path\for\the\log>

![apkshellext2 zip](https://cloud.githubusercontent.com/assets/485503/10458350/62b2dab0-7198-11e5-9b32-3747817493f4.png) (remove the .png)

Please send me the log after you check folders with apk files and ipa files.

BTW, can you send me the ipa files, I'm just interested in why they are failed to show.

**Comment by steelew** [comment]
There is no HKEY_LOCAL_MACHINE\SOFTWARE\SHARPSHELL to change. Also, I changed the default program from winrar to ApkShellext2.dll (that didn't work) but I am seeing the tool tip for .apk's.

**Comment by kkguo** [comment]
You suppose to add that key.
tool tip showing up proves the handler register is ok. just somehow the icon handler setting doesn't work.
What did you see now on apk files? an empty icon or something else?
Change default program will not work, as it's not "opener" program.

**Comment by steelew** [comment]
I'm not totally sure how to add all of that.

**Comment by steelew** [comment]
For .apk (with winrar as opener) I see the winrar icon, with the .dll, it was just a white square. I do see the tool tip on .apk's as well

**Comment by kkguo** [comment]
So just import this reg file
![sharpshell reg](https://cloud.githubusercontent.com/assets/485503/10460043/8ddccd56-71a0-11e5-8109-12865d07e3a9.png)

**Comment by steelew** [comment]
I looked at the cmd window when i tried using the uninstall.bat. It looks like I need to have adb.exe installed. Is this apkshellex2 dependant on having adb installed or the sdk?

![need adb](https://cloud.githubusercontent.com/assets/4789852/10475523/6a3918ec-71f9-11e5-8065-79318dce1d28.png)

**Comment by kkguo** [comment]
no, adb is not needed, for now.
I noticed that you are using a path including a space, can you remove the space and try again?

**Comment by kkguo** [comment]
@steelew Please check if you still have problem in the latest release, I'm going to close this, please feel free to re-open once you have problem.

**Comment by steelew** [comment]
Same, still not working. Thanks for the help but I'm just gonna be done with this.

**Comment by kkguo** [comment]
Hey, Hang up budy. 
If you have time and if you don't mind, I can send you a debug version, I can see more info from the log which generated from it.
Or we can do a conf-call, and I can check what is going on on your computer..

**Comment by wulinfa** [comment]
@kkguo 
Can't work in my Win7Sp1/64bit too. Maybe cause of 7zip in your conflict list?
But it doesn't make sense, for the old version 2,3,5000,10854 runs perfect before I installed the latest release v0.1.5961.26220 @ Apr.27.2016.
Now I have to change back to the original version 2,3,5000,10854. It works, but I am not happy.
