### ISSUE TITLE
Debug vs Release variable for renaming APKs

### ISSUE THREAD

**Issue by coreyog** [allangoing/apkshellext#50]
The APKs manifest should indicate if the APK is "debuggable." I know the play store can determine if I am trying to upload a debug build so it seems possible.

**Comment by kkguo** [comment]
Hi, @coreyog , I'm not really sure which part is indicating debug/release within apk file, can you send me 2 samples? one for debug and one for release version?

**Comment by coreyog** [comment]
Here are Debug and Release apk's for my alarm clock app. If I try to upload DEBUG.apk to the Play Market I'm not allowed and it tells me that it's a debuggable apk (I believe it has a debuggable attribute in the Android Manifest). RELEASE.apk is fully signed and would be accepted as non-debuggable.

DEBUG: https://dl.dropboxusercontent.com/u/2509448/DEBUG.apk
RELEASE: https://dl.dropboxusercontent.com/u/2509448/RELEASE.apk

The app is free so I'm not worried about it being available here.

**Comment by sylveon** [comment]
Somewhere in your androidmanifest.xml of the debug version, there is the line:
d e b u g g a b l e  
In the release, there is no such line.

**Comment by kkguo** [comment]
Hi, @coreyog, Sorry for letting you wait so long, can you send me the DEBUG.apk again? as I cannnot find it anymore.
restarting...

**Comment by coreyog** [comment]
I have restored DEBUG.apk and RELEASE.apk in my dropbox. The links are:

https://dl.dropboxusercontent.com/u/2509448/DEBUG.apk
https://dl.dropboxusercontent.com/u/2509448/RELEASE.apk

**Comment by kkguo** [comment]
fixed by release v0.1.5961.24160

**Comment by coreyog** [comment]
I just tried it. It always says Release.

I set my Rename Pattern to: `%AppName%_%Version%_%Debuggable%`

On my DEBUG.apk and RELEASE.apk files provided above, both files are renamed to "Dysania_1.9_Release.apk"

**Comment by kkguo** [comment]
Sorry, check the updated release, 26220

**Comment by kkguo** [comment]
Sorry, check the updated release, 26220

**Comment by kkguo** [comment]
@coreyog, does it work for you?

**Comment by coreyog** [comment]
Sorry about the delay. Yes, it's working perfectly on my APKs. I really appreciate the work you've put into it.

**Comment by kkguo** [comment]
Cool
