### ISSUE TITLE
Does not work in Windows 10 x64

### ISSUE THREAD

**Issue by GuyInDogSuit** [allangoing/apkshellext#51]
Latest version from October 2015 does not work. No options in context menu, no APK icons.

**Comment by kkguo** [comment]
Hi, @GuyInDogSuit 
Is the issue resolved?
can you read #46, and try again?

BR,
KK

**Comment by GuyInDogSuit** [comment]
Still doesn't work. Wondershare MobileGo has hijacked the icons and I could
never get them working.

---

_"We are all searching for someone whose demons play well with ours."_

**Comment by sylveon** [comment]
> _"We are all searching for someone whose demons play well with ours."_  

I̶̧ͦ̓̈́ͣͭ͆͐̍̀̒ͦͮͪͮ̔ͯ̅t̴̷͛̍̏ͩ͊͐̒ͯ̃͛͞.̢̨͒̉ͬ̊ͬ̑ͪ̒ͮ̒̄̏ͪ̃ͫ̄̔.̆̀̍̉̽̉̒͊ͣ͗̔̒ͫ͌͡.̛͊̾̓̍̓͋́̿̅̈́͢͡ ͋̄̋̊̈͂̿̿̑͊̉̂͋͐҉̢̀͟͡a̶̶͂͐ͧ̋̏ͨͥͯl̷̛ͦ̈́̃̋̓̒̏̀͘͘͟w͑ͥ̓̊́ͨ̎̄ͩͯ̂̿͌͗̀́͡aͮͯ͌̎͑̽̄ͪ̐̈̾̌̋̉҉̨͟͟͝y̡ͭ̓ͨ͑̅ͬ̒̿̑̈́̋̓͑ͬ̌͛͂͐̚̕s̢̨̓ͩͫͤ̎ͣ͂ͯ̅͋ͧͤ.̶̅̽͆͐͒ͬ͊̄͗̇ͪ͜.̷̧ͧͨ̀ͭ̽͝͝.̶̊ͬͧͣ̋͂̍ͩ̚͟ ̑̽ͤ̆̒͋ͣ̅̆̅̒͐́͌̉̎́͟ẅ̐ͬ͐́̿̆̀̕o͌ͫ̒̍̃̾ͧ̏̑̊̔̾̅̂̄ͨͫ҉r̴̵͆͗̅̇͊̄ͦͨ̍̅̌̽ͭ̊̈́͒͢ķ̵̶͛̏͐̽̑̉̑͆ͤ̂ȩͤ͐̋̇̊̃ͫ̆͆̅ͦ̅͌́̚͡҉d̷̸̏̃̑̂͢҉͠.̿̉ͬ̆̒̀ͫ̎̎́͘͜͞͠.͒̍ͯͩ̑҉̛͜͠.̵̷̨̛ͪ̋ͤ̆ͪ̌͟   

I managed to get it working.
If you navigate to `HKEY_CLASSES_ROOT\.apk`, there should be a default value already set. Let's say it's `apkfile`.  
Then browse to `HKEY_CLASSES_ROOT\apkfile` and copy everything from `HKEY_CLASSES_ROOT\.apk` to `HKEY_CLASSES_ROOT\apkfile` except the default value.

**Comment by sylveon** [comment]
Let me know if this won't work or you don't know how copy them.  
PS: Don't forget to restart after

**Comment by GuyInDogSuit** [comment]
I don't see this "apkfile"

---

_"We are all searching for someone whose demons play well with ours."_

**Comment by sylveon** [comment]
Can you export `HKEY_CLASSES_ROOT\.apk` as a reg file (Right-click -> Export) and post it here?  
With that I should be able to fix your problem.

**Comment by kkguo** [comment]
@charlesmilette , thanks for your answers, please continue on supporting people here!
@GuyInDogSuit , can you uninstall MobileGo and re-run install.bat again?
HKEY_CLASSES_ROOT.apk will be set to different value by different application, not always "apkfile".

**Comment by GuyInDogSuit** [comment]
Uninstalling MobileGo didn't solve the issue.

---

_"We are all searching for someone whose demons play well with ours."_

**Comment by kkguo** [comment]
@GuyInDogSuit , like @charlesmilette said, can you dump the registry?

**Comment by GuyInDogSuit** [comment]
How?

---

_"We are all searching for someone whose demons play well with ours."_

**Comment by kkguo** [comment]
regedit
right click on HKEY_CLASSES_ROOT.apk,
Export
save the file and past it here.

**Comment by sylveon** [comment]
Or simply type `reg export HKCR\.apk registeryentry.reg` in a command line.
Then type `notepad registeryentry.reg`.
Notepad will open with text already in it.
Copy-paste the content here

**Comment by GuyInDogSuit** [comment]
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT.apk]

[HKEY_CLASSES_ROOT.apk\DefaultIcon]
@="%1"
"SharpShell_Backup_DefaultIcon"="%1"

[HKEY_CLASSES_ROOT.apk\shellex]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers]

[HKEY_CLASSES_ROOT.apk\shellex\ContextMenuHandlers\ApkContextMenu]
@="{dcb629fc-f86f-456f-8e24-98b9b2643a9b}"

[HKEY_CLASSES_ROOT.apk\shellex\IconHandler]
@="{1f869cee-4fda-35d9-896f-43975a87d1f6}"

[HKEY_CLASSES_ROOT.apk\shellex{00021500-0000-0000-C000-000000000046}]
@="{946435a5-fe96-416d-99db-e94ee9fb46c8}"

[HKEY_CLASSES_ROOT.apk\shellex{e357fccd-a995-4576-b01f-234630154e96}]
@="{d747c5a7-2f66-4b7d-8301-8531838e4ed3}"

**Comment by GuyInDogSuit** [comment]
Did you get that?

---

_"We are all searching for someone whose demons play well with ours."_

**Comment by kkguo** [comment]
I didn't see problem from the register keys here, so several question.
Your OS version, home edition? UAC setting? does it work before?
if you want to try an older version, you can find from 
https://github.com/kkguo/apkshellext/tree/releases

and at last, it might not help but you can alias .apk to another key, and put all the settings under the alias key, something like:
[HKEY_CLASSES_ROOT.apk\DefaultIcon]
@="APKFILE"

[HKEY_CLASSES_ROOT\APKFILE\shellex]

[HKEY_CLASSES_ROOT\APKFILE\shellex\ContextMenuHandlers]

[HKEY_CLASSES_ROOT\APKFILE\shellex\ContextMenuHandlers\ApkContextMenu]
@="{dcb629fc-f86f-456f-8e24-98b9b2643a9b}"

[HKEY_CLASSES_ROOT\APKFILE\shellex\IconHandler]
@="{1f869cee-4fda-35d9-896f-43975a87d1f6}"

[HKEY_CLASSES_ROOT\APKFILE\shellex{00021500-0000-0000-C000-000000000046}]
@="{946435a5-fe96-416d-99db-e94ee9fb46c8}"

[HKEY_CLASSES_ROOT\APKFILE\shellex{e357fccd-a995-4576-b01f-234630154e96}]
@="{d747c5a7-2f66-4b7d-8301-8531838e4ed3}"

**Comment by kkguo** [comment]
@GuyInDogSuit and can you find this string in your registery "{1f869cee-4fda-35d9-896f-43975a87d1f6}" and list all the matches? this is the iconhandler's GUID

**Comment by AndroidDeveloperLB** [comment]
Any news about this? I also can't use this plugin anymore on Windows 10...

**Comment by kkguo** [comment]
I'm closing it now, if anyone still see problem, please feel free to re-open this.

**Comment by AndroidDeveloperLB** [comment]
I still see the problem. Why close it?
Maybe I don't install it correctly?
I tried to run-as-admin on "install.bat" , restart Explorer process myself or via "restart_explorer.bat" ...

**Comment by kkguo** [comment]
I thought this is long time ago. Did you try the latest?

**Comment by AndroidDeveloperLB** [comment]
@kkguo Actually seems to be the same as here:
https://github.com/kkguo/apkshellext/issues/78#event-2404389843

**Comment by kkguo** [comment]
merge with #78
