### ISSUE TITLE
Why can't display Simplified Chinese ?

### ISSUE THREAD

**Issue by donniean** [allangoing/apkshellext#52]
Hello !

Why can't display Simplified Chinese on Windows 10 x64 ?

The language is "中文(中华人民共和国)" (Simplified Chinese) .

At last, excuse for my poor English .

**Comment by kkguo** [comment]
我可以说中文
这个问题好像和以前另一个人的问题相似, 选择其他语言的时候有用吗?
我需要你提供一下你的系统原始语言,以及你现在使用的语言.

**Comment by donniean** [comment]
除了简体中文 其他都有用
我的系统的原始语言应该是中文的 现在用的语言也是简体中文

**Comment by mapleshadow** [comment]
靠，搞了半天原来是国人开发的。。。。。。。。
顶个！

**Comment by kkguo** [comment]
I'm making another release to use the native satellite dll for multi-language, and probably a auto download option,  just another several days :)
我决定改用微软原先的解决方案来解决多语言问题, 然后再加一个自动下载的选项.再等几天吧:)

**Comment by donniean** [comment]
好的 thanks 
good job !

**Comment by kkguo** [comment]
fixed by release v0.1.5961.24160

**Comment by kkguo** [comment]
fixed by release v0.1.5961.24160

**Comment by donniean** [comment]
新版的好像 什么语言切换都没用了。。。 只能用英文的了 = =

**Comment by kkguo** [comment]
mmm,,在zip里面有好几个文件夹,一种语言有一个,每一个文件夹下面都有一个dll文件,把这些都解压出来,请你确认一下
mmm,there are several folders within the zip package, every folder for one language, and every folder has a dll underneath, can you please extract them and confirm again?

**Comment by donniean** [comment]
你是指的这样吗
![1](https://cloud.githubusercontent.com/assets/12584040/15357058/222ce632-1d2f-11e6-8d59-7a76fbb40467.png)
![2](https://cloud.githubusercontent.com/assets/12584040/15357059/23244594-1d2f-11e6-8a89-e8be6eb8b8f4.png)

**Comment by kkguo** [comment]
没错，这样可以选择语言吗？
right，is it OK now？

**Comment by donniean** [comment]
选不了。。。 选了还是英文。
