### ISSUE TITLE
German translation looks very English

### ISSUE THREAD

**Issue by rekire** [allangoing/apkshellext#55]
In other words nothing happens when I select a different language. Btw I'll try to update your translations when I find some free time.

**Comment by kkguo** [comment]
Now i got reports like language selection doesn't work, trying to fix

**Comment by rekire** [comment]
I can confirm that :(

I'm right now translating the new strings. What does that translation mean?

> For avoiding situation of same Version but different revision number, this most like happens in android app files. By checking this, rename app file as %AppName%_%Version%_%Revision%, otherwise, use %AppName%_%Version%.

I guess you are referring apks with the same version name but different version code. However the text is hardly understandable if you are not a developer IMHO.

**Comment by rekire** [comment]
FYI German translation is done (except of that above)

**Comment by kkguo** [comment]
Sorry for confuse, I'm not native, but don't worry, this string is
deprecated, will not show anywhere.
