### ISSUE TITLE
How To Find Update of APk..

### ISSUE THREAD

**Issue by Aashik-github** [allangoing/apkshellext#56]
Hello I am New user and I also new here ......

I installed apkshellext and it successfully work on my Pc

I found the apk update option on Right click 

But I Have No idea about How to download new update file using apkshell ext and how to view update are available or Not  

i Show the update option in the apkshellext home page

![screenshot](https://cloud.githubusercontent.com/assets/20092841/16271911/88c60cc8-38bb-11e6-9015-09166f10f168.png)

**Comment by kkguo** [comment]
Hi,
I understand the wording is confusing, sorry for that.
If you open up the preference window, you will find a string probably under
language selection and tells you are on the latest or there is a newer
version.
KK

**Comment by Aashik-github** [comment]
oh, Ok Thanks
