### ISSUE TITLE
Can't unmount/eject/safe-removal of external drive...?

### ISSUE THREAD

**Issue by ryanzeus31** [allangoing/apkshellext#58]
I can't eject or safely remove my external drive (HDD,FDD,any) if I see and/or touch an APK file on them, it said my drive in use, I think it cause by apkshellext. Anything normal if I not see or touch any APK file on that drive since first time I plug the drive in.

**Comment by kkguo** [comment]
looks like another handler leak like #60

**Comment by kkguo** [comment]
close
