### ISSUE TITLE
icon doesnt show in moborobo file explorer

### ISSUE THREAD

**Issue by astonvilla682** [allangoing/apkshellext#59]
<a href="http://tinypic.com?ref=2h86dki" target="_blank"><img src="http://i63.tinypic.com/2h86dki.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by astonvilla682** [comment]
in windows 10 & 8 & 8.1 same problem.
but in win 7 its ok.

**Comment by kkguo** [comment]
I cannot support any tool other than windows explorer.
