### ISSUE TITLE
Apk Cannot Delete

### ISSUE THREAD

**Issue by Aashik-github** [allangoing/apkshellext#60]
When i am Trying To Delete a folder with apk or asingle apk it won't delete

Older Version of Apkshellext are working Fine ....

and Removal Disk Cannot Remove Safely ....

**Comment by kkguo** [comment]
Please let me know the apk name, version, your os, apkshellext version.

**Comment by Daringbaaz** [comment]
Same Problem Here,

Some of app Won't Delete ,

It says it used on explorer,

i used to Delete That Types of Apk

with iobit unlocker,

It will Re Delete that types of apk and Re Start Explorer,

That Types of Folder also won't delete Which contains Some apk,

**Comment by kkguo** [comment]
Does every apk behave like this, or just certain apk files?
if later, please send me a copy of your apk file.
