### ISSUE TITLE
Bug: Can't show VectorDrawable icon of APK files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [allangoing/apkshellext#62]
As an example, download this APK :
http://forum.xda-developers.com/android/apps-games/app-contacts-sync-sync-contacts-photos-t3483461

On a device, it will show the icon, but not here, because here it tries to decode PNG/JPG image file, instead of VectorDrawable file.

**Comment by kkguo** [comment]
adaptive icon support is in my list

**Comment by AndroidDeveloperLB** [comment]
@kkguo I wrote VectorDrawable here. Not adaptive icon.
But both are important, and there could even be a combination of the two.
In fact, nowadays, when I create a new project, it actually contains a combination of the two:

![image](https://user-images.githubusercontent.com/5357526/59536285-f29fb880-8efb-11e9-85bb-4a710fb12bbc.png)

**Comment by kkguo** [comment]
VectorDrawable partially supported since 2.0.5

**Comment by AndroidDeveloperLB** [comment]
@kkguo Partially in which way?
What's not supported?
And if it's only partially, why close this ?
