### ISSUE TITLE
Thumbnailing doesn't work in some 3rd-party file managers

### ISSUE THREAD

**Issue by rmenessec** [allangoing/apkshellext#65]
For example, thumbnailing doesn't work for [XYplorer](https://www.xyplorer.com/). (Free trial available to test with.)

Any idea why this would be?

Thanks!

**Comment by sylveon** [comment]
does it works with other shell extensions (word documents for example)?

**Comment by rmenessec** [comment]
It displays default icons associated in the Registry correctly for all common file types. The only dynamic icon generator I have / use at the moment is APKShellExt, so I can't make a direct comparison there. Instead of using whatever icon bitmap APKShellExt is making available, it's displaying an "unknown document" icon. I think it's %SystemRoot\System32\imageres.dll,2.

IoW: static icons work fine. Also icons (in EXEs that contain them) display correctly in XYplorer. I assume that APKShellExt is generating icons using some method that's not the same as or similar to the way Windows extracts and renders EXE icons for display.

Everything else icon-related works as expected in XYplorer, such as icons, including the ones I've defined with manual Registry editing, in context menus.

I've rebooted a couple of times to rule out a DLL registration issue. Before and after rebooting, Windows Explorer (7 SP1 x64, all rollups) was immediately displaying icons generated by APKShellExt.

I'm concerned that this could be some architecture issue; XYplorer is available as an x86 binary only.

**Comment by sylveon** [comment]
Most probably. Try installing the x86 version of APKShellExt

**Comment by rmenessec** [comment]
@charlesmilette I'm not sure where that would be. I have the latest release installed. It consists of one .NET DLL. I was under the impression that .NET DLLs do not contain native code, except for the Win32 EXE stub.

**Comment by sylveon** [comment]
so it's probably a x64 dll then.

you'll have to build it yourself.

**Comment by rmenessec** [comment]
@charlesmilette No, it's a .NET / [C#](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)) DLL, containing .NET bytecode that does not execute directly on any CPU designed or sold by any manufacturer.

It is translated into machine code at runtime.

**Comment by rmenessec** [comment]
![apkshell](https://cloud.githubusercontent.com/assets/425616/26038721/e7613416-38dc-11e7-8db1-74807a65dd9b.png)

**Comment by kkguo** [comment]
@rmenessec , you are right, it's a .NET dll, and has significant difference than traditional MFC code.
Upon .net 4.0, it (Microsoft) said they are fully supporting managed shell extension with .net.
I don't know exactly the details, but the released code is compiled for ”Any platform“ in VS 2015,  you should be able to compile it as x86 or x64 specifically.
You may try to compile as 32bit x86 platform binary to see if it works.

**Comment by sylveon** [comment]
Probably that the DLL isn't registered in the wow6432node of the registry
(so it isn't registered for 32 bits apps)

Le lun. 15 mai 2017 13:34, Jingang Guo, KK <notifications@github.com> a
écrit :

**Comment by rmenessec** [comment]
@kkguo There's nothing for me to "try to compile". **It's already compiled.** The DLL you're providing has been compiled to intermediate bytecode, and is ready to be executed by the .NET JIT loader.

http://stackoverflow.com/questions/601974/clr-vs-jit

@charlesmilette Your response is both completely wrong and not useful. Yes, it's registered under HKCR\Wow6432Node.

**Comment by kkguo** [comment]
@rmenessec , I thought you were compiling the source code. And even it's .net managed code, it still has x86/x64/AnyPlatform compile option and I believe they are trying to resolve compatibility issues.
For your issue, one possible debug method is hook up the call from XYplorer to COM interface, I hope I can have bandwidth this weekend.

**Comment by rmenessec** [comment]
@kkguo No, I'm using your compiled DLL, as released. Sorry for the confusion.

I'm not certain what you mean about compatibility issues. Are you saying that there's a problem with the CLR JIT component? Something to do with running x86 JIT code on x64 platforms? I don't follow Microsoft's .NET development or related project development closely, but I know they've had other JIT problems in the past, so I'd tend to believe that.

For what it's worth, I was running .NET 4.6.2 when I opened the issue, and I'm running 4.7 now. There haven't been any noticeable changes. The [4.7 release notes](https://support.microsoft.com/en-us/help/4015088/known-issues-in-the-net-framework-4-7) don't mention any known issues related to code generation, JIT, or WOW... but I don't know how many, if any, known issues carry over to 4.7 from previous releases.

Or are you referring to a problem in Visual Studio or the WIndows or .NET SDKs? MSVS 2017 is now available, again with [a full "Community" release for free](https://www.visualstudio.com/downloads/), and the 15.1 update with .NET 4.7 targeting was released a few weeks ago. Do you think it might be worth updating to the new toolchains?

Sadly, I don't have the resources to set up my own development environment right now.

At any rate—yes, if you can find the time to test XYplorer or other 32-bit-only file managers against APKShellExt, it would be greatly appreciated.

Thanks!

**Comment by kkguo** [comment]
I found several articles, and looks like .net is still not ok for in-process extension.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd758089(v=vs.85).aspx#acceptable_uses_of_managed_code_and_other_runtimes
https://blogs.msdn.microsoft.com/oldnewthing/20130222-01/?p=5163

As I didn't continue the dev for a while, is it the time to think about re-write it again??? 🤢

**Comment by rmenessec** [comment]
Ordinarily, I wouldn't volunteer anyone else's time, but... since you ask... yes, a rewrite wouldn't necessarily be a bad idea.

C# and other JIT languages tend to have odd limitations, performance issues, an oddly high rate of memory leaks, and other assorted problems compared to well-written code that's expected to compile to native CPU instructions. Even though the code's supposedly cross-platform and machine-neutral, it also tends to run into architecture and platform problems that "shouldn't" exist.

My understanding is that [C++11](https://en.wikipedia.org/wiki/C%2B%2B11
) (supported by Visual Studio) is much easier to write in than C++ was originally. There are complete C++11 toolchains for virtually every platform in existence, and good toolkits like [Qt](https://www.qt.io/) seem to ease the pain of trying to develop GUI applications for very different OSes.

The site does not make it easy to tell, but you can obtain the complete Qt SDK for Windows for free.

**Comment by kkguo** [comment]
The problem is not the language, it's MFC, my last time use MFC is like 12
years ago, and I still remember the pain...
Well, will do some research and think about this.

rmenessec <notifications@github.com>于2017年5月19日周五 上午3:22写道：

**Comment by rmenessec** [comment]
@kkguo Use Qt instead of MFC, like I suggested. 😀

**Comment by sylveon** [comment]
Isn't MFC the API to write shell extensions?

**Comment by rmenessec** [comment]
@charlesmilette Maybe start with the Wikipedia articles.
