### ISSUE TITLE
Can 't Rename Folder?

### ISSUE THREAD

**Issue by oneplus25** [allangoing/apkshellext#67]
Step....
1. Folder have apk file.
2. Rename apk file.
3. Rename Folder ...But can 't rename folder.
It 's show

![1](https://user-images.githubusercontent.com/29035044/26908121-daab9cc6-4c22-11e7-946f-17ba808bb926.jpg)

PS. Windows 7 Ultimate 64

**Comment by kkguo** [comment]
same thing as #60
