### ISSUE TITLE
Won't show icon as WinRar is default program for oppening apk

### ISSUE THREAD

**Issue by NightMean** [allangoing/apkshellext#68]
So I installed this and it worked perfectly but I had to open one apk in winrar but I missclicked to make it as default,now I'm struggling to remove winrar as default one,I searched on google and found that deleting something in registry will remove it but it didn't so did something like this happend to anyone else ?

**Comment by kkguo** [comment]
probably re-install will resolve this temporarily. But winrar will
overwrite it again.
I'm not using winrar so I cannot give you an accurate answer, but you
should find an file associate window in winrar's option.
HKEY_CLASSES_ROOT\.apk\shellex\IconHandler it the key you want to find,
firstly this key should exist, and the value should be {
1F869CEE-4FDA-35D9-896F-43975A87D1F6}

NightMean <notifications@github.com>于2017年8月27日周日 下午12:17写道：

**Comment by NightMean** [comment]
I tried to reinstall and it didn't work :/ 
the key is the same however winrar is overwriting it anyway.

**Comment by kkguo** [comment]
not sure if this is still an issue, feel free to re-open
