### ISSUE TITLE
Locks empty apk files

### ISSUE THREAD

**Issue by ggets** [allangoing/apkshellext#70]

**Comment by kkguo** [comment]
maybe it has handler leaks if exception happened during reading apk files. if possible, please elaborate how to reproduce the problem?

**Comment by kkguo** [comment]
leave only one open

**Comment by ggets** [comment]
Sorry I though I wrote some text, but apparently it got lost. Reproducing is easy. Open your downloads folder in advance and try to download an apk there. I'm using Windows 10 1809 x64 and Firefox, but I guess that doesn't matter much. It tries to read the empty file and locks it and firefox can't write to it when the download is finished.
