### ISSUE TITLE
shadowsocks-android无法显示图标啊

### ISSUE THREAD

**Issue by LsnmxNB** [allangoing/apkshellext#74]
https://github.com/shadowsocks/shadowsocks-android/releases

![snipaste_2018-11-19_16-10-09](https://user-images.githubusercontent.com/42826027/48693857-af0af780-ec15-11e8-94e3-7a9f3ad0030e.png)

**Comment by LsnmxNB** [comment]
@kkguo 现很多类似这样的都不能显示啊，有时间更新一下吧

**Comment by kkguo** [comment]
it should work now. close this.
