### ISSUE TITLE
New Offizially Repository ? Where is KKguo ?

### ISSUE THREAD

**Issue by blackcrack** [allangoing/apkshellext#75]
Hi,

there is no update and Release of apkshellext for Windows,
can anyone maybe overtake this Project, because there is no release since Apr 27, 2016
https://github.com/kkguo/apkshellext/releases

This is a super tool for WinNT from Vista up to 10 for handle and managing
the apk's for our Android Devices in Windows.
This is worth for developing further and therewith want i make a call / appeal 
for further programming and make a officially repository, 
maybe with more members for have a possible for handle 
in the next years with more as one members.. 

so, who whant maintain this and want build up a apk-group to handle 
something like apkshellext ...

there be manny repositorys, maybe also updated
so, why not create again a offizially apkshellext repository with more as one member ?

@abazad abazad / apkshellext
@aihacker aihacker / apkshellext
@AungMyintOo AungMyintOo / apkshellext
@cnandroidlib cnandroidlib / apkshellext
@cormen3 cormen3 / apkshellext
@crazyants crazyants / apkshellext
@dokxpi dokxpi / apkshellext
@funagi funagi / apkshellext
@inkimagine inkimagine / apkshellext
@iwonasado iwonasado / apkshellext
@JaviLerma JaviLerma / apkshellext
@jawad6233 jawad6233 / apkshellext
@jindaxia jindaxia / apkshellext
@jitendersrivastava jitendersrivastava / apkshellext
@JohnEdwardMS JohnEdwardMS / apkshellext
@Kasijjuf Kasijjuf / apkshellext
@KING-TV KING-TV / apkshellext
@Kreashions Kreashions / apkshellext
@loveezu loveezu / apkshellext
@lucapug lucapug / apkshellext
@luislasonbra luislasonbra / apkshellext
@Mah3svara Mah3svara / apkshellext
@mapleshadow mapleshadow / apkshellext
@MinChanSike MinChanSike / apkshellext
@mixzine mixzine / apkshellext
@mohammedajaroud mohammedajaroud / apkshellext
@Ms-Julia Ms-Julia / apkshellext
@muink muink / apkshellext
@najibalghaeth najibalghaeth / apkshellext
@Navasesh Navasesh / apkshellext
@NeneNeko NeneNeko / apkshellext
@neopack1 neopack1 / apkshellext
@Netscape007 Netscape007 / apkshellext
@phaufe phaufe / apkshellext
@rajeshwarn rajeshwarn / apkshellext
@rdavydov rdavydov / apkshellext
@ScorpionIbm ScorpionIbm / apkshellext
@sengkyaut sengkyaut / apkshellext
@shayanw shayanw / apkshellext
@socrotolovro socrotolovro / apkshellext
@suvjunmd suvjunmd / apkshellext
@SykesMod SykesMod / apkshellext
@tandori tandori / apkshellext
@temp10min temp10min / apkshellext
@toumingyu toumingyu / apkshellext
@traien traien / apkshellext
@wahidmounir wahidmounir / apkshellext
@weiling103 weiling103 / apkshellext
@YuanjieWang YuanjieWang / apkshellext 

best regards
Blacky

**Comment by kkguo** [comment]
Hey, I'm still alive :)
Basically I don't have much time to do develop apart from work and family. But I'm still here.
Please let me know your priority regarding expected features, I'm starting to do works now.
BTW, I'm active on telegram group.

KK

**Comment by blackcrack** [comment]
hey i am happy to hear something of you :) I thought it would be happened something ..
well then, good to hear .. i am not at telegram or something social media ..(crap).. *s*

the important is, i have realize to have change the packet versions and 
the actual version of this programm can't it read anymore and therewith 
no prossible for extract the icon and maby different other datas and 
no possible to check if it some packets be untouched or so.. can it be ?

so in direction of android 6 and so on and the packetmanagement..
so maybe a other/new version of apk's maybe wheres no more supported.. or so..
and should updated in your programm .. maybe..

so, best greetings to you family out from the net :)
and you have right, make slow and let your self a bit time to breathing, it is a must have ! :+1: 

and thank you very much for this nice Explorer-enhancement  :)

best regards
Blacky

**Comment by kkguo** [comment]
Thanks @blackcrack , yes, newer apk has different format or structure if they are following the new methodology. please feel free to send me example which doesn't work, I need them to debug. If you think it violates copy right, send me a link.

I'm closing this now, please feel free to re-open it if you have other concern.
