### ISSUE TITLE
Folders That Have Apk Files Can't Do Rename Or Remove Or Cut

### ISSUE THREAD

**Issue by desperanish** [allangoing/apkshellext#76]
Hello To Everyone
In Windows 7 64Bit Apk File Do Not Have Any Problem And I Can Any Want To Do.
But Folders That Have Apk Files Can't Do Rename Or Remove Or Cut.
If Take An Hour You Can Do Any Work Unless You Go In To The Folder That Have Apk.
Please Consider It.
Thanks

**Comment by kkguo** [comment]
Can you please help to debug? Please check which file caused the folder lock? You could try copy one apk in a folder and tries to delete it. You might need to restart explorer sometimes to release the apk and folder.
After that, please send me that apk file, so that I can see what locks the file.

**Comment by kkguo** [comment]
refer to #70

**Comment by kkguo** [comment]
closed due to no response.
