### ISSUE TITLE
Translator NEEDED!! according Release v2.0.5

### ISSUE THREAD

**Issue by blackcrack** [allangoing/apkshellext#80]
Hi,

according https://github.com/kkguo/apkshellext/releases/tag/v2.0.5
set i am up this issue for speak about..

so, well i am an german. who do you need, what should be translated ?

best
Blacky

**Comment by kkguo** [comment]
please refer to https://github.com/kkguo/apkshellext/wiki/Translation-and-Multi-language-support

**Comment by blackcrack** [comment]
what you do :) ![AltText](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-1/bf.gif)  \*nod nod*  ![AltText](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-1/cv.gif) 
and i am do it on [efb.nu](https://www.essential-freebies.de/board/viewtopic.php?f=6&t=18791&p=151744&hilit=apkshell#p152405 "essential-freebies.de") 

![AltText](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-0/drag01.gif)

 ![AltText](http://www.blackysgate.de/files/folder-root/smilys/kolobok.us-1/cy.gif)

**Comment by kkguo** [comment]
alright, thanks for translation, you could create a translated README page and I can merge it to mainstream.

**Comment by blackcrack** [comment]
@kkguo 
heeyy, why closeing ? We need a still Translates, this issue helps for "link they in"
and give information in Github. Can you reopen it and maybe sticky if possible ?
best regards..
p.s.: German 100%

**Comment by kkguo** [comment]
Thanks!
Translators are always needed, Do you think this need to keep open? Suppose only issue tracking here.

**Comment by blackcrack** [comment]
jepp, keep it open for let the other show this need who be always a issue to the other,
if they are open it, then see they are the link and the conversation about :smiley: 
so, reopen and if possible, pinning on top.
