### ISSUE TITLE
not working with .appx file

### ISSUE THREAD

**Issue by sandriaas** [allangoing/apkshellext#82]
# Steps to reproduce

```
1. installing latest apkshellext and enabling these option
- [x] Display WindowsPhone app (appx. appxbundle) icon.
- [x] Show menu to Microsoft Store (for appx/appxbundle)

2. downloading appx file via store.rg-adguard.net to try (sharex, spotify, asphalt 8)
```

# Expected behavior

```
showing icon nor context menu for appx and appxbundle file type
```

# Actual behavior

```
the icon nor context menu isn't showing at all
```

# Environment data

```
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18936 N/A Build 18936
```

**Comment by sandriaas** [comment]
anyone?

**Comment by blackcrack** [comment]
@kkguo  

Hi Sandria,
why do you have not a description ?

**Comment by kkguo** [comment]
@andrizmitnick , please follow https://github.com/kkguo/apkshellext/wiki/Quick-check-before-raise-issue to detail your issue.

**Comment by sandriaas** [comment]
@blackcrack @kkguo hi sorry, i thought my title is straight forward already. i just edited the description now. thanks before

**Comment by kkguo** [comment]
Looks like windows10 hijacks the control of appx files. icon handler and menu handler doesn't work but tooltip handler works.
I will try to find more to read about this. I labeled this as a bug.

**Comment by Masamune3210** [comment]
Could it be due to the fact that appx is also the file type for windows store apps, so windows treats it specially?

**Comment by kkguo** [comment]
Yes, that's what I meant

**Comment by kkguo** [comment]
I think I find a solution for this, it's probably the same issue as #78 , "Open with" is taking control of showing icon on top of apkshellext, to fix it you need to remove the key in the registry:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.appx

But this will remove the feature of  "double-click to open", and the icon will be override again once you chose to open it with appinstaller...
Trying to find a solution for this...

**Comment by kkguo** [comment]
@deadair3210 , please feedback, or I can close this.

**Comment by Masamune3210** [comment]
Wasn't the op, just put my 2 cents in

**Comment by kkguo** [comment]
Oh, sorry
@andrizmitnick, any feedback?

**Comment by sandriaas** [comment]
@kkguo hi, sorry for being late. the workaround is working fine. i thought there might be some fix, but it seems it's just a limitation in windows itself. so, sure we can close this. 

thanks guys!!

**Comment by kkguo** [comment]
close now
