### ISSUE TITLE
APKS ?

### ISSUE THREAD

**Issue by blackcrack** [allangoing/apkshellext#85]
Hi, 

i have see a apks on the apk universe, 
is this official ? and if yes, maybe a supporting for extracting and let show the icon too ?

@kkguo mail me on : myname @blackysgate.de and i can give you a sample.

best regards
Blacky

**Comment by kkguo** [comment]
I don't quite understand what you mean, but you could contact me at issue@apkshellext.com

**Comment by kkguo** [comment]
@blackcrack , the apk you send me, the FlashLight_HD_LED_Pro, it has a blank icon, extract the androidmanifest.xml, you can see the icon path is res/mipmap-mdpi-v4/ic_launcher.png

BTW, the apk itself is suspicious, it has a package name as com.sigmacolors.cactuscoloringbook, and applies for lots of sensitive permission, it maybe inserted by that website when it cracking the apk, but I strongly recommend you DO NOT install this apk, and also DO NOT download anything from that site anymore.

**Comment by blackcrack** [comment]
resolved|wontfix :+1:  hihi..
ayeaye, i remove it from rss :)
